language: 
  - cpp

compiler:
  - clang
  - gcc

script:
  - cd ~/build/martinmoene/gsl-lite/test
  - $CXX -std=c++0x -Wall -I../include/gsl -Dgsl_CONFIG_THROWS_FOR_TESTING=1 -o gsl-lite.t gsl-lite.t.cpp assert.t.cpp at.t.cpp not_null.t.cpp owner.t.cpp span.t.cpp string_span.t.cpp util.t.cpp && ./gsl-lite.t && ./gsl-lite.t --list-tests
